version: "3.4"

networks:
  frontend:

services:

  web:
    build: frontend/
    ports:
      - 3001:3001
    volumes:
      # Share the entire project except "node_modules". This prevents us from having to COPY the project files
      #   in the Dockerfile, while still keeping separate node dependency files.
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    networks:
      - frontend
    depends_on:
      - api
